-- SQL is normally used when you need to store and manage structured data in a relational database,
--  while NoSQL is better suited for managing unstructured or semi-structured data without 
--  relationships. If you need to query your data, SQL databases are ideal, while NoSQL solutions 
--  work best when you need to store large amounts of data and access it quickly.




-- Vertical scaling is the process of increasing a server's computing power by adding more CPUs, 
-- memory, or storage. Horizontal scaling is the process of increasing a server's computing power 
-- by adding more servers, nodes or virtual machines to the cluster. Both strategies can be used 
-- to support increased demand, but vertical scaling is usually more cost-effective in the short
--  term, while horizontal scaling allows for greater scalability and flexibility in the long term.